### ISSUE TITLE
Building the website

### ISSUE THREAD

**Issue by BCaven** [BCaven/creativity-optional-vue#1]
Right now the base page is [bcaven.github.io](https://bcaven.github.io/)
So the site is stored at [bcaven.github.io/creativityoptional](https://bcaven.github.io/creativityoptional/)

- [x] make a different url
     - [ ]  this might mean making a github user called `creativity-optional` or something similar

**Comment by AnarBayanzul** [comment]
instead of trying to change the url, why don't we just build the website on the original repo?

**Comment by BCaven** [comment]
[vue's recommended deployment method](https://cli.vuejs.org/guide/deployment.html#github-pages)

is to have the vue project in one repo and deploy the `/dist` folder to a second repo. Github pages just displays the second repo.

This will end up looking like this:

we have three repos: `creativity-optional`, `creativity-optional-vue`, and `creativity-optional-website`
`creativity-optional` is the actual project
`creativity-optional-vue` is the vue project
`creativity-optional-website` is effectively just the `/dist` folder from `creativity-optional-vue`

Of course, deployment will be automated so as far as we are concerned there are only *two* repositories to care about: `creativity-optional` and `creativity-optional-vue`

**Comment by BCaven** [comment]
# End result:

this repository holds the vue source project

to build the project, run `./deploy.sh`
the deployed project can be found in [this](https://github.com/BCaven/creativityoptional) project.

The github pages site is [here](https://bcaven.github.io/creativityoptional/)

# for future reference:

we can clean up the deployment process (by making it use npm) as seen in [this tutorial](https://blog.logrocket.com/automatically-build-deploy-vuejs-app-github-pages/) but that is the subject of a different discussion.
